# Generated by Django 5.2.17 on 2026-09-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_tag', models.CharField(default='Gıda güvenliği ve iklim eğitimi', max_length=120)),
                ('hero_title', models.CharField(default='Gıdanın yolculuğunu öğren, geleceği birlikte koru.', max_length=255)),
                ('hero_description', models.TextField(default='İklimKiti ile gıda güvenliği, sürdürülebilir yaşam ve iklim değişikliği hakkında öğren, keşfet ve oyunlarla kendini geliştir.')),
                ('relationship_title', models.CharField(default='Gıda ve iklim ilişkisi', max_length=200)),
                ('relationship_lead', models.CharField(default='Yediğimiz her gıdanın arkasında su, toprak, enerji, emek ve taşıma süreçleri bulunur.', max_length=255)),
                ('relationship_body', models.TextField(blank=True, default='Bu süreçleri tanımak, hem kendi seçimlerimizi hem de gezegenimizin geleceğini daha bilinçli değerlendirmemize yardımcı olur.')),
                ('assistant_title', models.CharField(default='İklimKiti Asistanı', max_length=200)),
                ('assistant_description', models.TextField(default='Gıda güvenliği, gıda israfı, su kaynakları ve sürdürülebilir yaşam hakkında kısa sorular sorabilirsiniz.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ana sayfa içeriği',
                'verbose_name_plural': 'Ana sayfa içeriği',
            },
        ),
        migrations.CreateModel(
            name='HomeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.homepagecontent')),
            ],
            options={
                'verbose_name': 'Ana sayfa eylem önerisi',
                'verbose_name_plural': 'Ana sayfa eylem önerileri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
