# Generated by Django 5.2.17 on 2026-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeathonGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gıda ve eğitim için iklim çözümü stüdyosu', max_length=220)),
                ('subtitle', models.CharField(default='COP31 Maarif İklim İdeathonu için kanıttan prototipe uzanan çalışma alanı', max_length=255)),
                ('introduction', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COP31 proje rehberi',
                'verbose_name_plural': 'COP31 proje rehberi',
            },
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('prompt', models.TextField(blank=True)),
                ('score_weight', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.ideathonguide')),
            ],
            options={
                'verbose_name': 'Rehber bölümü',
                'verbose_name_plural': 'Rehber bölümleri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
