# Generated by Django 6.0.4 on 2026-09-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ideathonguide_guidesection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Alındı'), ('blocked', 'Engellendi'), ('answered', 'Yanıtlandı')], default='received', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_prompt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistan prompt kaydı',
                'verbose_name_plural': 'Asistan prompt kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
