from django.core.management.base import BaseCommand

from learning.models import GlossaryTerm, Topic


TERMS = [
    ('Adaptasyon', 'İklim değişikliğinin mevcut ve beklenen etkilerine uyum sağlamak için alınan önlemlerdir. Kuraklığa dayanıklı ürün seçmek, okulun sıcak hava planı hazırlaması veya suyu verimli kullanan sulama sistemine geçmek adaptasyona örnektir. Proje yazarken adaptasyonun hangi riski azalttığını ve kimlerin daha güvenli hâle geldiğini açıkça belirtin.'),
    ('Adil geçiş', 'Düşük karbonlu ve sürdürülebilir bir ekonomiye geçerken hiçbir grubun geride bırakılmamasını ifade eder. Bir okul projesi yalnızca teknik olarak başarılı değil, farklı gelir düzeylerinden ve farklı öğrenme ihtiyaçlarından öğrencilerin katılabileceği kadar erişilebilir olmalıdır.'),
    ('Agroekoloji', 'Tarımı ekolojik ilkelerle birlikte tasarlayan yaklaşımdır. Toprak canlılığını, biyoçeşitliliği, yerel bilgiyi, su verimliliğini ve üreticinin geçimini aynı sistem içinde düşünür. Okul bahçesi veya yerel üretici projesinde tek ürüne değil, ekosistem ilişkilerine bakmayı sağlar.'),
    ('Açık veri', 'Kişisel ve hassas bilgiler korunarak herkesin erişebildiği, yeniden kullanılabilen veridir. İklim ve gıda projesinde resmî istatistikleri, ölçüm yöntemini ve veri tarihini belirtmek iddianın güvenilirliğini artırır.'),
    ('Biyoçeşitlilik', 'Bir ekosistemdeki gen, tür ve yaşam alanı çeşitliliğidir. Biyoçeşitlilik; tozlaşma, zararlıların dengelenmesi, toprağın korunması ve gıda seçeneklerinin devamlılığı için önemlidir. Proje göstergesi olarak gözlenen tür sayısı veya yerel bitki çeşitliliği izlenebilir.'),
    ('Biyolojik mücadele', 'Zararlılarla kimyasal yükü artırmadan doğal düşmanlar ve ekolojik yöntemlerle mücadele etmektir. Sürdürülebilir tarımda toprak ve su sağlığını korur; uygulama planında güvenlik ve uzman danışmanlığı gerekir.'),
    ('Birincil veri', 'Proje ekibinin doğrudan topladığı gözlem, ölçüm, anket veya görüşme verisidir. Okulda bir hafta tartılan gıda artığı birincil veridir. Tarih, yöntem, ölçüm birimi ve sorumluyu kaydetmeden veri kanıt gücünü kaybeder.'),
    ('Bütüncül yaklaşım', 'Bir sorunu yalnızca tek bir sonuç üzerinden değil; çevre, ekonomi, sağlık, eğitim ve adalet ilişkileriyle birlikte değerlendirmektir. Gıda israfını azaltırken beslenme güvenliğini, mutfak iş yükünü ve öğrenci katılımını da hesaba katmak bütüncül yaklaşımdır.'),
    ('Cinsiyet duyarlı iklim eylemi', 'İklim etkilerinin ve kaynaklara erişimin farklı grupları aynı biçimde etkilemediğini dikkate alan planlamadır. Öğrenci verileri toplanırken gönüllülük, mahremiyet ve ayrımcılık karşıtlığı korunmalıdır.'),
    ('Döngüsel ekonomi', 'Ürün ve malzemelerin mümkün olduğunca uzun süre değerini koruduğu, atığın tasarım aşamasında azaltıldığı ekonomik modeldir. Gıda için önleme, güvenli paylaşım, yeniden değerlendirme ve kompost adımlarını; yalnızca geri dönüşümden daha geniş bir çerçevede ele alır.'),
    ('Ekolojik ayak izi', 'Bir kişinin, kurumun veya ürünün kullandığı kaynakları ve oluşturduğu çevresel baskıyı ifade eden göstergedir. Projede ayak izi kullanırken kapsamı, veri kaynağını ve hesap varsayımlarını belirtin; tek bir sayı her şeyi anlatmaz.'),
    ('Ekosistem hizmetleri', 'Doğanın insanlara sağladığı su filtreleme, tozlaşma, karbon tutma, serinletme ve toprak oluşumu gibi faydalardır. Bir okul bahçesi projesi yalnızca estetik değil, gölge, habitat ve öğrenme alanı üreten bir altyapı olarak değerlendirilebilir.'),
    ('Emisyon', 'Bir kaynaktan atmosfere salınan gaz veya parçacıklardır. Proje metninde emisyon azaltımını iddia etmek yerine hangi faaliyet, hangi başlangıç değeri ve hangi ölçüm yöntemiyle azaltılacağını gösterin.'),
    ('Emisyon faktörü', 'Bir faaliyet birimi başına oluşan tahmini emisyon miktarıdır. Örneğin enerji, ulaşım veya atık hesabında kullanılan faktörün kaynağı ve yılı belirtilmelidir; tahmin ile doğrudan ölçüm birbirine karıştırılmamalıdır.'),
    ('Gıda güvenliği', 'Gıdanın üretimden tüketime kadar fiziksel, kimyasal ve biyolojik tehlikelerden korunmuş, yeterli ve erişilebilir olması durumudur. İklim değişikliği sıcaklık, su kıtlığı, üretim ve depolama risklerini artırabildiği için güvenliği dayanıklılık planıyla birlikte ele alınır.'),
    ('Gıda kaybı', 'Gıdanın hasat, taşıma, depolama ve üretim aşamalarında tüketiciye ulaşmadan azalması veya niteliğini yitirmesidir. Kaynağı doğru belirlemek, çözümün tarlada mı, depoda mı, mutfakta mı kurulacağını gösterir.'),
    ('Gıda israfı', 'Tüketiciye, perakendeye veya yemek hizmetine ulaşmış yenilebilir gıdanın tüketilmeden atılmasıdır. Porsiyon, menü, satın alma, saklama ve davranış kararlarıyla ilişkilidir; okul pilotunda kilogram ve neden birlikte izlenmelidir.'),
    ('Gıda sistemi', 'Üretim, işleme, taşıma, pazarlama, tüketim ve atık yönetiminin oluşturduğu bütündür. Güçlü bir proje bir halkayı iyileştirirken diğer halkada yeni sorun üretmediğini açıklamalıdır.'),
    ('İklim adaleti', 'İklim krizinin sorumluluğu ve etkilerinin toplumlar arasında eşit olmadığını kabul eden yaklaşımdır. Çözüm tasarlarken kırılgan grupların riskini, söz hakkını ve faydaya erişimini görünür kılar.'),
    ('İklim direnci', 'Bir kişi, okul, şehir veya ekosistemin iklim şoklarına hazırlanma, etkilenme sırasında işlevini sürdürme ve sonrasında öğrenerek güçlenme kapasitesidir. Pilotun yalnızca iyi günde değil, sıcak hava veya su kesintisi gibi senaryolarda da çalışması test edilmelidir.'),
    ('İklim okuryazarlığı', 'İklim sistemini, değişimin nedenlerini ve sonuçlarını anlayıp güvenilir bilgiyle karar verme ve eyleme geçme becerisidir. Öğrencinin veri okuması kadar belirsizliği ve farklı çözüm seçeneklerini tartabilmesi de bu becerinin parçasıdır.'),
    ('Karbon ayak izi', 'Bir faaliyet, kişi veya ürünün doğrudan ve dolaylı sera gazı salımlarının karbondioksit eşdeğeriyle ifade edilmesidir. Kapsam, zaman aralığı, veri kaynağı ve hesap yöntemi yazılmadan verilen karbon sayısı karşılaştırılamaz.'),
    ('Karbon yutağı', 'Atmosferden karbonu emen ve depolayan doğal veya teknolojik sistemdir. Ormanlar, topraklar ve sulak alanlar doğal yutak örnekleridir; yutak iddiası yapılırken süreklilik, bakım ve izleme planı açıklanmalıdır.'),
    ('Karbon nötr', 'Belirli bir kapsamda salınan emisyonların azaltım ve doğrulanmış dengeleme adımlarıyla net olarak sıfırlanmasını hedefleyen durumdur. Önce gerçek azaltım, sonra dengeleme ilkesi korunmalıdır.'),
    ('Kırılgan grup', 'İklim risklerinden daha fazla etkilenebilen veya uyum kaynaklarına erişimi sınırlı olan gruptur. Yaş, sağlık, gelir, engellilik, mekân ve bakım sorumlulukları kırılganlığı etkileyebilir; proje planında mahremiyet korunmalıdır.'),
    ('Kuraklık', 'Yağışın uzun süre normalin altında kalması ve su talebiyle arzı arasındaki dengenin bozulmasıdır. Kuraklık planı yalnızca daha az su kullanmayı değil, gıda üretimi, sağlık, adil paylaşım ve erken uyarıyı da kapsar.'),
    ('Life cycle / yaşam döngüsü', 'Bir ürünün ham maddeden üretime, taşımaya, kullanıma ve kullanım sonrasına kadar bütün aşamalarının incelenmesidir. Bir çözümün bir aşamada kazandırıp başka bir aşamada daha fazla kaynak tüketip tüketmediğini görmeyi sağlar.'),
    ('Metan', 'Kısa vadede atmosferi güçlü biçimde ısıtan bir sera gazıdır. Organik atıkların oksijensiz ortamda parçalanması metan oluşturabilir; gıda israfını önlemek hem kaynak kaybını hem de atık kaynaklı emisyon riskini azaltır.'),
    ('Mikroplastik', 'Çevrede bulunan çok küçük plastik parçacıklardır. Gıda ambalajı, su ve atık çalışmaları yapılırken tek kullanımlık malzeme azaltımı, doğru veri ve sağlık iddialarında dikkatli kaynak kullanımı gerekir.'),
    ('Mutfak atığı', 'Yemek hazırlama ve tüketim sırasında ortaya çıkan organik veya ambalaj kaynaklı atıktır. Atığı kaynağında ayırmak, miktar kadar bileşimi de görmeyi ve kompost veya önleme kararını doğru vermeyi sağlar.'),
    ('OB8 Sürdürülebilirlik Okuryazarlığı', 'Sürdürülebilirlik sorunlarını anlama, sistemler arası ilişki kurma, kanıta dayalı karar verme, sorumluluk alma ve eylemi değerlendirme becerilerinin bütünüdür. İklim projesi bilgi, beceri, tutum ve eylemi görünür ürünlerle göstermelidir.'),
    ('Ölçülebilir etki', 'Bir projenin çevresel veya sosyal sonucunun başlangıç değeri, hedefi, zaman aralığı ve yöntemiyle izlenebilmesidir. “Farkındalık arttı” yerine test puanı, katılım oranı, kilogram atık veya litre su gibi göstergeler kullanılır.'),
    ('Önleme hiyerarşisi', 'Atık yönetiminde önce oluşumu önleme, sonra azaltma, yeniden kullanma, geri dönüştürme ve en son bertaraf etme sırasını ifade eder. Gıda için en değerli çözüm çoğu zaman atık oluşmadan önce planlama yapmaktır.'),
    ('Pilot uygulama', 'Bir fikrin sınırlı ölçekte, belirli süre ve göstergelerle denenmesidir. İyi pilotun hedef kitlesi, sorumlusu, takvimi, bütçesi, risk planı ve başarısızlıkta değiştirilecek varsayımı bulunur.'),
    ('Sera gazı', 'Atmosferde ısı tutarak küresel sıcaklık dengesini etkileyen gazlardır. Karbondioksit, metan ve diazot monoksit önemli örneklerdir; farklı gazlar karşılaştırılırken karbondioksit eşdeğeri kullanılır.'),
    ('Sürdürülebilir kalkınma', 'Bugünün ihtiyaçlarını karşılarken gelecek kuşakların ihtiyaçlarını karşılama kapasitesini azaltmayan kalkınma yaklaşımıdır. Çevre, toplum ve ekonomi birlikte değerlendirilmeden sürdürülebilirlik iddiası eksik kalır.'),
    ('Sürdürülebilir tarım', 'Toprağı, suyu, biyoçeşitliliği ve üreticinin geçimini uzun vadede koruyan tarım yaklaşımıdır. Verim kadar kaynak kullanımı, dayanıklılık, adalet ve yerel koşullara uyum da ölçülür.'),
    ('Su ayak izi', 'Bir ürün, kişi veya kurumun tükettiği suyun doğrudan ve üretim zincirindeki dolaylı bileşenlerini ifade eder. Hesapta ürünün kaynağı, üretim yöntemi ve veri belirsizliği açıkça yazılmalıdır.'),
    ('Su verimliliği', 'Aynı ihtiyacı daha az su ve daha az kayıpla karşılamaktır. Kaçakların giderilmesi, doğru zamanlama, uygun teknoloji ve davranış değişikliği birlikte ele alındığında kalıcı olur.'),
    ('Tedarik zinciri', 'Bir ürünün hammadde ve üreticiden tüketiciye ulaşana kadar geçtiği kişi, kurum, süreç ve taşıma ağıdır. Gıda projesi tedarik zincirindeki sıcaklık, mesafe, ambalaj ve kayıp noktalarını izleyebilir.'),
    ('Toprak organik maddesi', 'Bitki ve canlı kalıntılarından oluşan, toprağın su tutma, besin sağlama ve yapı özelliklerini etkileyen bileşendir. Artması toprak dayanıklılığını destekleyebilir; iddialar yerel ölçüm ve uzmanlıkla doğrulanmalıdır.'),
    ('Yaşam döngüsü analizi', 'Bir ürün veya hizmetin çevresel etkilerini tüm yaşam döngüsü boyunca sistematik olarak değerlendirme yöntemidir. Proje karşılaştırmalarında sınırların ve varsayımların aynı tutulmasını sağlar.'),
    ('Yeşil beceriler', 'Kaynak verimliliği, yenilenebilir enerji, döngüsel ekonomi, çevresel veri, ekolojik tasarım ve sürdürülebilir kararlarla ilgili bilgi ve uygulama becerileridir. Öğrenci projesi bu becerileri somut görevlerle göstermelidir.'),
]

TERMS.extend([
    ('Aşırı hava olayı', 'Bir bölgede alışılmış iklim koşullarına göre sıra dışı şiddette veya sıklıkta görülen sıcaklık, yağış, rüzgâr ya da fırtına olayıdır. Gıda üretiminde ürünleri, altyapıyı ve tedarik süreçlerini etkileyebilir.'),
    ('Atmosfer', 'Dünya’yı çevreleyen gaz katmanıdır. Güneş enerjisinin tutulması ve dağıtılması iklimi şekillendirir; sera gazlarının artması atmosferin enerji dengesini değiştirir.'),
    ('Atmosferik karbondioksit', 'Atmosferde bulunan ve başlıca fosil yakıt kullanımı ile arazi değişiklikleri sonucu artan bir sera gazıdır. Bitkiler fotosentez sırasında karbondioksit kullanır; ancak bu doğal süreç insan kaynaklı salımların tümünü kendiliğinden dengelemez.'),
    ('Azot döngüsü', 'Azotun atmosfer, toprak, su ve canlılar arasında farklı biçimlerde dolaşmasıdır. Tarımda azotlu gübrelerin doğru miktarda ve zamanda kullanılması ürün gelişimi ile su ve hava kirliliği riskleri açısından önemlidir.'),
    ('Bağıl nem', 'Havadaki mevcut su buharı miktarının aynı sıcaklıkta havanın tutabileceği en yüksek miktara oranıdır. Sıcaklık ve nem birlikte gıdaların kurumasını, depolama koşullarını ve insan konforunu etkileyebilir.'),
    ('Besin ağı', 'Bir ekosistemde canlıların beslenme yoluyla birbirine bağlandığı ilişkiler bütünüdür. Tarım alanlarındaki çeşitlilik ve doğal yaşam alanları bu ilişkilerin sürmesine katkı sağlar.'),
    ('Besin döngüsü', 'Karbon, azot ve fosfor gibi elementlerin toprak, su, hava ve canlılar arasında dolaşmasıdır. Sağlıklı toprak ve dengeli tarım uygulamaları bu döngülerin devamını destekler.'),
    ('Besin güvencesi', 'İnsanların sağlıklı ve aktif bir yaşam için yeterli, güvenli ve besleyici gıdaya sürekli fiziksel ve ekonomik erişebilmesidir. Gıda bulunabilirliği, erişim, kullanım ve istikrar boyutlarını içerir.'),
    ('Beslenme güvenliği', 'Gıdaya erişimin yanı sıra güvenli su, sağlık, bakım ve uygun beslenme koşullarının bir arada bulunmasıdır. Yeterli gıdanın mevcut olması tek başına dengeli beslenmeyi garanti etmez.'),
    ('Biyobozunur atık', 'Mikroorganizmaların uygun koşullarda parçalayabildiği organik atıktır. Gıda artıkları bu gruba girebilir; atığın ayrı toplanması kompost veya biyogaz gibi uygun yöntemleri mümkün kılar.'),
    ('Biyogaz', 'Organik maddelerin oksijensiz ortamda parçalanmasıyla oluşabilen, metan içeren gaz karışımıdır. Uygun tesislerde enerji üretiminde kullanılabilir; oluşan gazın güvenli biçimde yakalanması gerekir.'),
    ('Biyokütle', 'Bitki, hayvan veya organik atık kaynaklı biyolojik maddelerdir. Enerji ve malzeme üretiminde kullanılabilir; çevresel etkisi kaynağa, üretim biçimine ve arazi kullanımına bağlıdır.'),
    ('Biyolojik çeşitlilik koridoru', 'Yaşam alanlarını birbirine bağlayarak canlıların hareket etmesine ve popülasyonlar arasındaki etkileşime yardımcı olan doğal veya düzenlenmiş alandır. Tarım alanlarının ekolojik bağlantısını destekleyebilir.'),
    ('Bitki örtüsü', 'Bir alanda doğal olarak yetişen veya yetiştirilen bitkilerin bütünüdür. Toprağı erozyondan korur, su döngüsünü etkiler ve pek çok canlıya yaşam alanı sağlar.'),
    ('Bulutluluk', 'Gökyüzünün bulutlarla kaplı bölümünü ifade eder. Bulutlar güneş ışığının yeryüzüne ulaşmasını ve yeryüzünden yayılan ısının atmosferde tutulmasını etkileyerek hava ve iklim süreçlerinde rol oynar.'),
    ('Çapraz bulaşma', 'Mikroorganizmaların veya alerjenlerin bir gıdadan başka bir gıdaya, yüzeye ya da ekipmana taşınmasıdır. Temiz ekipman kullanmak ve çiğ gıdaları hazır gıdalardan ayrı tutmak riski azaltır.'),
    ('Çevresel sürdürülebilirlik', 'Doğal kaynakları ve ekosistemleri uzun vadede koruyarak bugünkü ihtiyaçları karşılama yaklaşımıdır. Gıda üretiminde toprak, su, enerji ve biyoçeşitlilik üzerindeki etkileri birlikte değerlendirmeyi gerektirir.'),
    ('Çiğ noktası', 'Havanın soğuyarak su buharıyla doygun hâle geldiği sıcaklıktır; bu noktada yoğuşma başlayabilir. Depolama ve soğuk zincirde yoğuşmanın gıda ve ambalaj üzerindeki etkileri dikkate alınır.'),
    ('Dağıtım kaybı', 'Gıdanın taşıma ve dağıtım aşamalarında bozulma, hasar veya lojistik sorunlar nedeniyle tüketilemez hâle gelmesi ya da kaybolmasıdır. Uygun taşıma ve planlama bu kayıpları azaltmaya yardımcı olur.'),
    ('Dayanıklı tohum', 'Kuraklık, sıcaklık veya hastalık gibi belirli streslere daha iyi dayanabilen özellikler taşıyan tohumdur. Uygun tohum seçimi yerel koşullara göre yapılmalı; tek başına bütün iklim risklerini ortadan kaldırdığı düşünülmemelidir.'),
    ('Deniz seviyesi yükselmesi', 'Küresel ortalama deniz seviyesinin, okyanusların ısınarak genleşmesi ve kara buzlarının erimesi gibi nedenlerle artmasıdır. Kıyı tarımını, tatlı su kaynaklarını ve gıda altyapısını etkileyebilir.'),
    ('Depolama kaybı', 'Gıdanın uygun sıcaklık, nem veya hijyen koşullarında tutulamaması nedeniyle depolama sırasında miktar ya da kalite kaybetmesidir. Ürüne uygun koşullar ve düzenli kontrol kayıpları azaltır.'),
    ('Dışsallık', 'Bir üretim veya tüketim faaliyetinin, bedeli doğrudan işlemi yapanlarca karşılanmayan çevresel ya da toplumsal etkisidir. Örneğin kirlilik maliyetleri gıda fiyatına yansımayabilir.'),
    ('Dönüşümlü otlatma', 'Hayvanların meradaki farklı bölümlere sırayla alınarak bitki örtüsünün yeniden gelişmesine zaman tanıyan otlatma yöntemidir. Uygun planlandığında mera sağlığını destekleyebilir; aşırı otlatmayı tek başına önlemez.'),
    ('Dünya sistemi', 'Atmosfer, okyanuslar, buzullar, kara yüzeyi ve canlıların karşılıklı etkileşim hâlindeki bütünüdür. Bir bölümdeki değişim diğer bölümleri ve gıda üretim koşullarını etkileyebilir.'),
    ('Ekim nöbeti', 'Aynı tarlada farklı bitki türlerinin belirli bir sırayla yetiştirilmesidir. Toprak verimliliğini korumaya, hastalık ve zararlı baskısını azaltmaya yardımcı olabilir.'),
    ('El Niño', 'Pasifik Okyanusu’nun tropikal bölümünde deniz yüzeyi sıcaklıklarının dönemsel olarak yükselmesiyle ilişkili iklim olayıdır. Dünya’nın farklı bölgelerinde yağış ve sıcaklık düzenlerini etkileyebilir; etkiler bölgeden bölgeye değişir.'),
    ('Erken uyarı sistemi', 'Tehlike oluşmadan önce risk bilgisi ve anlaşılır uyarıları ilgili kişilere ulaştıran izleme, tahmin ve iletişim düzenidir. Tarım ve gıda hizmetlerinin aşırı hava olaylarına hazırlanmasına yardımcı olabilir.'),
    ('Erozyon', 'Toprak parçacıklarının su, rüzgâr veya başka etkenlerle taşınarak bulunduğu yerden uzaklaşmasıdır. Bitki örtüsünü korumak ve toprağı çıplak bırakmamak erozyon riskini azaltabilir.'),
    ('Buharlaşma', 'Sıvı suyun ısı alarak su buharına dönüşmesidir. Sıcaklık, rüzgâr ve nem bu süreci etkiler; tarımda bitkilerin su ihtiyacı ve sulama planı üzerinde önem taşır.'),
    ('Fenoloji', 'Bitkilerin çiçeklenme, yapraklanma ve olgunlaşma gibi dönemsel gelişim evrelerini ve bunların zamanlamasını inceleyen bilim alanıdır. Sıcaklık değişimleri bu evrelerin zamanını etkileyebilir.'),
    ('Fosil yakıt', 'Kömür, petrol ve doğal gaz gibi, eski canlı kalıntılarından uzun jeolojik süreçlerde oluşan yakıttır. Yakıldığında karbondioksit ve başka kirleticiler açığa çıkarabilir.'),
    ('Fotosentez', 'Bitkilerin, alglerin ve bazı mikroorganizmaların ışık enerjisiyle karbondioksit ve sudan organik madde üretme sürecidir. Bitkisel gıdanın ve tarımsal üretimin temelini oluşturur.'),
    ('Gıda erişilebilirliği', 'İnsanların gıdaya fiziksel ve ekonomik olarak ulaşabilmesidir. Ulaşım, gelir, fiyatlar, dağıtım altyapısı ve toplumsal eşitsizlikler erişimi etkileyebilir.'),
    ('Gıda bulunabilirliği', 'Bir bölgede insanların tüketebileceği yeterli miktarda gıdanın üretim, stok, ithalat veya yardım yoluyla mevcut olmasıdır. Gıdanın mevcut olması, herkesin ona erişebildiği anlamına gelmez.'),
    ('Gıda fiyat oynaklığı', 'Gıda fiyatlarının kısa dönemlerde belirgin biçimde değişmesidir. Hava olayları, üretim miktarı, enerji maliyetleri ve tedarik sorunları fiyatları etkileyebilir.'),
    ('Gıda lojistiği', 'Gıdanın üretim yerinden işleme, depolama ve dağıtım noktalarına uygun koşullarda taşınması ve planlanmasıdır. Soğuk zincir ve rota planlaması kayıpları azaltabilir.'),
    ('Gıda okuryazarlığı', 'Gıdayı seçme, anlama, hazırlama, saklama ve tüketme konusunda bilgiye dayalı karar verebilme becerisidir. Etiketleri ve saklama talimatlarını değerlendirmek bu becerinin parçasıdır.'),
    ('Gıda özerkliği', 'Toplulukların kendi gıda sistemlerini şekillendirme ve üretim ile tüketim kararlarına katılma hakkı ve kapasitesidir. Yerel üreticilerin söz hakkı ve kültürel gıda tercihleriyle ilişkilidir.'),
    ('Gıda paylaşımı', 'Tüketilebilir durumdaki fazla gıdanın güvenli biçimde ihtiyaç duyan kişi veya kurumlara ulaştırılmasıdır. Önce gıda fazlasını oluşmadan önlemek, paylaşımda ise hijyen ve izlenebilirliği sağlamak önemlidir.'),
    ('Gıda rezervi', 'Üretim veya tedarikte aksama olduğunda kullanılmak üzere saklanan gıda stokudur. Rezervlerin türü, miktarı ve saklama koşulları olası ihtiyaca göre planlanır.'),
    ('Gıda tedarik güvenliği', 'Gerekli gıdanın yeterli miktarda, güvenli ve kabul edilebilir koşullarda sürekli temin edilebilmesidir. İklim kaynaklı üretim ve ulaşım aksamaları bu güvenliği zorlayabilir.'),
    ('Gıda tedarik zinciri', 'Gıdanın üreticiden işleme, depolama ve dağıtım aşamalarından geçerek tüketiciye ulaşmasını sağlayan bağlantılı faaliyetler bütünüdür. Zincirdeki her aşama kalite ve kayıp üzerinde etkilidir.'),
    ('Gıda üretiminde enerji kullanımı', 'Tarım, sulama, işleme, soğutma ve taşıma için kullanılan enerjidir. Enerji kaynağı ve verimliliği, gıdanın maliyetini ve çevresel etkisini değiştirebilir.'),
    ('Gri su', 'Evsel kullanım sonrası oluşan, tuvalet atığı içermeyen duş, lavabo veya çamaşır suyu gibi atık sudur. Arıtma ve mevzuata uygunluk sağlanmadan gıda üretiminde veya içme amacıyla kullanılmamalıdır.'),
    ('Hasat sonrası kayıp', 'Ürünün hasattan tüketiciye ulaşana kadar taşıma, işleme veya saklama sırasında miktar ve kalitesini kaybetmesidir. Uygun ambalaj ve depolama kayıpları azaltmaya yardımcı olur.'),
    ('Hava kalitesi', 'Havadaki kirleticilerin miktarını ve insan sağlığı ile çevre üzerindeki etkilerini ifade eder. Toz, duman ve ozon gibi kirleticiler tarım çalışanlarını, bitkileri ve toplulukları etkileyebilir.'),
    ('Hava durumu', 'Belirli bir yerde ve kısa bir zaman aralığında görülen sıcaklık, yağış, rüzgâr ve nem gibi atmosfer koşullarıdır. Hava durumu kısa sürelidir; iklim ise uzun dönem örüntülerini anlatır.'),
    ('Hidrolojik döngü', 'Suyun buharlaşma, yoğunlaşma, yağış, yüzey akışı ve yeraltına sızma gibi süreçlerle Dünya üzerinde dolaşmasıdır. İklim değişikliği döngünün bazı bölgelerdeki yağış ve kuraklık düzenini etkileyebilir.'),
    ('Isı adası', 'Yapılaşmış kentsel alanların çevredeki kırsal alanlardan daha sıcak olma eğilimidir. Ağaç gölgesi, geçirgen yüzeyler ve yeşil alanlar yerel sıcaklığı azaltmaya yardımcı olabilir.'),
    ('Isı stresi', 'Yüksek sıcaklık ve nem gibi koşullarda vücudun ısı dengesini korumakta zorlanmasıdır. Açık alanda çalışanlar ve hayvanlar risk altında olabilir; su, gölge ve uygun dinlenme önemlidir.'),
    ('İklim', 'Bir bölgenin hava koşullarının uzun yıllar boyunca gözlenen ortalama ve değişkenlik özellikleridir. Sıcaklık ve yağış örüntüleri tarımsal üretim ve gıda sistemleri için temel koşulları belirler.'),
    ('İklim değişikliği', 'İklim özelliklerinde uzun dönemli ve kalıcı değişimdir. Günümüzdeki hızlı değişimin başlıca nedeni insan faaliyetlerinden kaynaklanan sera gazı salımlarıdır.'),
    ('İklim finansmanı', 'İklim değişikliğini azaltma ve etkilerine uyum çalışmalarını desteklemek için sağlanan kamu, özel sektör veya uluslararası kaynaklardır. Kaynağın adil, etkili ve şeffaf kullanılması önemlidir.'),
    ('İklim göçü', 'İklim değişikliğiyle bağlantılı etkilerin insanların yaşadıkları yerden geçici veya kalıcı olarak ayrılmalarına katkıda bulunmasıdır. Göç kararları genellikle ekonomik, toplumsal ve çevresel birçok etkene bağlıdır.'),
    ('İklim hizmeti', 'İklim verisi ve bilgisinin belirli kullanıcıların kararlarına yardımcı olacak biçimde hazırlanıp sunulmasıdır. Mevsimsel tahminler çiftçilerin ekim ve su planlamasında kullanılabilir.'),
    ('İklim modeli', 'İklim sistemindeki fiziksel süreçleri ve etkileşimleri matematiksel olarak temsil eden bilgisayar aracıdır. Model sonuçları senaryolara ve varsayımlara dayanır; kesin hava tahmini olarak yorumlanmamalıdır.'),
    ('İklim nötrlüğü', 'Belirlenmiş bir kapsam ve zaman aralığında insan kaynaklı sera gazı salımlarını mümkün olduğunca azaltıp kalan salımları giderimlerle dengeleme hedefidir. Kapsam ve hesap yöntemi açıkça belirtilmelidir.'),
    ('İklim risk değerlendirmesi', 'İklim tehlikelerinin, maruz kalma durumunun ve kırılganlığın incelenerek olası sonuçların belirlenmesidir. Okul veya gıda projesinde riskleri önceliklendirmeye yardımcı olur.'),
    ('İklim senaryosu', 'Gelecekteki sera gazı salımları ve toplumsal gelişmeler için oluşturulan olası koşul anlatımıdır. Tek bir kesin gelecek değildir; planlamada farklı senaryolar karşılaştırılır.'),
    ('İklim sistemi', 'Atmosfer, okyanuslar, kara, buzullar ve canlıların etkileşiminden oluşan sistemdir. Güneş enerjisi ve sera gazları bu sistemin enerji dengesini etkiler.'),
    ('İklim ve gıda ilişkisi', 'İklim koşulları ile gıda üretimi, işlenmesi, taşınması, saklanması ve tüketimi arasındaki karşılıklı etkileşimdir. Gıda sistemi de enerji kullanımı ve arazi değişikliği yoluyla iklimi etkileyebilir.'),
    ('İklim kaynaklı verim kaybı', 'Sıcaklık, kuraklık, aşırı yağış veya zararlı baskısı gibi iklimle ilişkili etkenlerin ürün miktarını ya da kalitesini düşürmesidir. Etki ürüne, yere ve uyum uygulamalarına göre değişir.'),
    ('İklim uyumu', 'İklimin mevcut veya beklenen etkilerine karşı riskleri azaltmak ve dayanıklılığı artırmak için yapılan düzenlemelerdir. Su tasarrufu ve sıcak hava planları uyum çalışmalarına örnek olabilir.'),
    ('İklim değişikliğini azaltma', 'Sera gazı salımlarını düşürmek veya atmosferden sera gazı giderimini artırmak için yapılan eylemlerdir. Enerji verimliliği ve fosil yakıt kullanımını azaltmak bu kapsamdadır.'),
    ('İklim kaynaklı afet', 'İklimle ilişkili bir tehlikenin toplumların maruziyeti ve kırılganlığıyla birleşerek ciddi kayıp ve aksamalara yol açmasıdır. Risk azaltımı, hazırlık ve erken uyarı zararları sınırlamaya yardımcı olur.'),
    ('Karbon bütçesi', 'Küresel ısınmayı belirli bir sınırın altında tutma olasılığıyla uyumlu olarak atmosfere salınabilecek toplam karbondioksit miktarına ilişkin tahmindir. Bilimsel varsayımlara ve seçilen sıcaklık hedefine bağlıdır.'),
    ('Karbon döngüsü', 'Karbonun atmosfer, okyanus, toprak, kayaçlar ve canlılar arasında dolaşmasıdır. İnsan kaynaklı fosil yakıt kullanımı bu döngüdeki atmosferik karbondioksit miktarını artırır.'),
    ('Karbon fiyatlandırması', 'Sera gazı salımlarına bir maliyet atayarak azaltım için ekonomik teşvik oluşturmayı amaçlayan politika yaklaşımıdır. Vergi ve emisyon ticaret sistemleri farklı uygulama örnekleridir.'),
    ('Karbon kaçağı', 'Bir bölgede emisyonları azaltmaya yönelik politika veya üretim değişikliğinin, faaliyetin başka bir bölgeye taşınmasıyla emisyonların orada artması riskidir. Değerlendirme tedarik zincirini de kapsamalıdır.'),
    ('Karbon kredisi', 'Belirli bir yöntemle hesaplanıp doğrulanmış sera gazı azaltımı veya giderimine karşılık gelen bir birimdir. Kalitesi ek ilavelik, kalıcılık ve bağımsız doğrulama gibi ölçütlere bağlıdır.'),
    ('Karbon piyasası', 'Sera gazı azaltım veya salım izinlerine ilişkin birimlerin kurallara göre alınıp satıldığı sistemdir. Piyasanın çevresel bütünlüğü izleme ve doğrulama kurallarına bağlıdır.'),
    ('Karbon yoğunluğu', 'Bir ürün, faaliyet veya ekonomik çıktı başına düşen sera gazı salımıdır. Karşılaştırma yaparken ölçüm sınırı, dönem ve kullanılan birimin aynı olması gerekir.'),
    ('Karbondioksit eşdeğeri', 'Farklı sera gazlarının iklimi ısıtma etkisini seçilen zaman aralığına göre karbondioksit miktarıyla karşılaştıran ölçü birimidir. Genellikle CO₂e biçiminde kısaltılır.'),
    ('Kentsel tarım', 'Sebze, meyve veya başka ürünlerin şehir içinde ya da yakın çevresinde yetiştirilmesidir. Yerel gıda erişimine katkı sunabilir; su, toprak güvenliği ve alan kullanımı dikkatle planlanmalıdır.'),
    ('Kıtlık', 'Bir nüfusun yeterli ve uygun gıdaya düzenli erişememesiyle ortaya çıkan ciddi gıda yoksunluğu durumudur. Yalnızca üretim azlığı değil, gelir ve erişim sorunları da kıtlığa yol açabilir.'),
    ('Kloroflorokarbon', 'Geçmişte soğutucu ve sprey ürünlerinde kullanılan, ozon tabakasına zarar verebilen ve güçlü sera etkisi bulunan insan yapımı gaz grubudur. Kullanımları uluslararası düzenlemelerle büyük ölçüde sınırlandırılmıştır.'),
    ('Kompost', 'Organik atıkların kontrollü biçimde ayrışmasıyla elde edilen, toprağa organik madde kazandırmakta kullanılabilen üründür. Güvenli kompost için uygun atık ve süreç koşulları gerekir.'),
    ('Kompostlaşma', 'Organik maddelerin çoğunlukla oksijenli koşullarda mikroorganizmalar tarafından parçalanması sürecidir. Nem, hava ve karışım dengesi sürecin sağlıklı ilerlemesine yardımcı olur.'),
    ('Konveksiyon', 'Isınan hava veya sıvının yükselip soğuyan kısmın yer değiştirmesiyle ısının akışkan içinde taşınmasıdır. Atmosferde bulut oluşumu ve yağış süreçlerinde rol oynar.'),
    ('Küresel ısınma', 'Dünya’nın uzun dönemli ortalama yüzey sıcaklığındaki artıştır. Başlıca nedeni insan faaliyetleriyle atmosfere eklenen sera gazlarıdır; iklim değişikliğinin önemli bir bileşenidir.'),
    ('Küresel ortalama sıcaklık', 'Dünya’nın farklı bölgelerindeki sıcaklık ölçümlerinin belirli bir yöntemle birleştirilmesiyle hesaplanan ortalama göstergedir. Tek bir yerdeki günlük sıcaklıkla aynı anlama gelmez.'),
    ('Kuraklığa dayanıklılık', 'Bir bitkinin veya tarım sisteminin su kısıtlı koşullarda işlevini sürdürme kapasitesidir. Çeşit seçimi, toprak yönetimi ve sulama planı birlikte değerlendirilmelidir.'),
    ('Kuraklık indeksi', 'Yağış, sıcaklık veya su dengesi gibi verilerden yararlanarak kuraklığın durumunu ve şiddetini izlemeye yarayan göstergedir. Kullanılan indeksin yöntemi ve zaman aralığı belirtilmelidir.'),
    ('Kuraklık izleme', 'Yağış, toprak nemi, akarsu ve benzeri göstergelerin düzenli gözlenerek kuraklık gelişiminin takip edilmesidir. Erken bilgi, su ve tarım kararlarının zamanında alınmasına yardımcı olur.'),
    ('Kuru tarım', 'Ürün yetiştirirken sulamaya çok az başvurulan veya hiç başvurulmayan, yağış ve toprak nemine dayalı tarım biçimidir. Uygun ürün ve toprak yönetimi bölgesel iklime göre seçilir.'),
    ('Mavi su', 'Nehir, göl ve yeraltı suyu gibi yüzey ve yeraltı kaynaklarında bulunan tatlı sudur. Sulama ve gıda üretiminde kullanımı havzanın su durumu ve diğer kullanıcıların ihtiyaçlarıyla birlikte ele alınmalıdır.'),
    ('Mevsimsel tahmin', 'Önümüzdeki haftalar veya aylar için sıcaklık ve yağışın mevsim normallerine göre nasıl olabileceğine ilişkin olasılıklı tahmindir. Günlük hava tahmini kadar kesin değildir.'),
    ('Mikroiklim', 'Yakın çevresinden farklı özellik gösterebilen küçük bir alanın iklim koşullarıdır. Bahçe duvarı, ağaç gölgesi, eğim ve yüzey türü ürünlerin yetişme koşullarını değiştirebilir.'),
    ('Miras tohumu', 'Belirli bir bölgede veya toplulukta uzun süredir yetiştirilen, kültürel ve tarımsal geçmiş taşıyan tohum çeşitleri için kullanılan terimdir. Özellikleri ve hukuki statüsü çeşide ve ülkeye göre değişebilir.'),
    ('Monokültür', 'Geniş bir alanda veya ardışık dönemlerde tek bir ürün türünün yetiştirilmesidir. Yönetimi kolaylaştırabilse de çeşitliliği azaltabilir ve bazı hastalık veya zararlılara karşı hassasiyeti artırabilir.'),
    ('Mutlak nem', 'Belirli bir hava hacminde bulunan su buharı kütlesidir. Hava sıcaklığı değişse de ölçüm birimi hacim başına su miktarını ifade eder; bağıl nemden farklı bir ölçüdür.'),
    ('Net sıfır emisyon', 'Belirli bir kapsamda insan kaynaklı sera gazı salımlarının derin biçimde azaltılması ve kalan salımların giderimlerle dengelenmesi hedefidir. Hedefin kapsamı ve takvimi açıkça belirtilmelidir.'),
    ('Nitrat', 'Toprak ve suda doğal olarak bulunabilen, azot içeren bir bileşiktir. Tarımda bitkilerin beslenmesi için önemlidir; aşırı gübre kullanımı su kaynaklarında nitrat artışına yol açabilir.'),
    ('Okyanus asitlenmesi', 'Okyanus suyunun atmosferden karbondioksit almasıyla kimyasal özelliklerinin değişip pH değerinin düşmesi sürecidir. Deniz canlılarını ve dolaylı olarak deniz ürünleri sistemlerini etkileyebilir.'),
    ('Organik tarım', 'Üretimde sentetik girdilerin kullanımını sınırlayan ve belirlenmiş standartlara uyan tarım sistemidir. Uygulama kuralları ülke ve sertifikasyon sistemine göre değişir; organik olması tek başına her çevresel etkinin düşük olduğu anlamına gelmez.'),
    ('Ormanlaştırma', 'Daha önce orman olmayan bir alanda orman örtüsü oluşturulmasıdır. Yerel ekosistem, su kaynakları ve uygun türler gözetilmelidir; her alana ağaç dikmek uygun bir çözüm değildir.'),
    ('Örtü bitkisi', 'Ana ürün yetişmediği dönemlerde toprağı örtmek ve korumak amacıyla ekilen bitkidir. Erozyonun azaltılmasına ve toprağın organik maddesinin desteklenmesine katkı sağlayabilir.'),
    ('Ötrofikasyon', 'Su ortamına aşırı besin maddesi, özellikle azot ve fosfor ulaşmasıyla alg ve bitki gelişiminin artması; oksijen dengesinin bozulabilmesi sürecidir. Gübre akışı ve atık sular nedenler arasında yer alır.'),
    ('Permafrost', 'En az iki yıl boyunca donmuş kalan toprak veya kaya tabakasıdır. Isınmayla çözülmesi, depolanmış organik maddelerin ayrışmasına ve sera gazı salımına yol açabilir.'),
    ('Pestisit', 'Zararlı organizmaları kontrol etmek amacıyla kullanılan madde veya ürün grubudur. Kullanımda etiket, mevzuat, insan sağlığı, tozlayıcılar ve çevresel etkiler gözetilmelidir.'),
    ('Polenleşme', 'Polenlerin çiçeklerin üreme organları arasında taşınması sürecidir. Arılar ve diğer tozlayıcılar birçok gıda bitkisinin üremesine katkı verir; yaşam alanlarının korunması önemlidir.'),
    ('Polikültür', 'Aynı alanda birden fazla bitki türünün birlikte veya planlı biçimde yetiştirilmesidir. Uygun tasarlandığında çeşitliliği ve ekolojik etkileşimleri artırabilir.'),
    ('Potansiyel evapotranspirasyon', 'Yeterli su bulunduğu varsayımı altında, belirli koşullarda toprak ve bitkilerden gerçekleşebilecek toplam buharlaşma-terleme miktarının tahminidir. Su ihtiyacı ve kuraklık değerlendirmelerinde kullanılır.'),
    ('Rasyonel sulama', 'Bitkinin ve toprağın ihtiyacına göre uygun miktarda, zamanda ve yöntemle su vermektir. Amaç gereksiz su kullanımını ve kayıpları azaltırken ürünün su ihtiyacını karşılamaktır.'),
    ('Rejeneratif tarım', 'Toprak sağlığını ve ekosistem işlevlerini iyileştirmeyi amaçlayan tarım uygulamaları bütünüdür. Terimin tanımı ve ölçütleri değişebildiğinden kullanılan uygulama ve göstergeler açıklanmalıdır.'),
    ('Sıcaklık anomalisi', 'Bir dönemde ölçülen sıcaklığın seçilmiş uzun dönem ortalamasından ne kadar farklı olduğunu gösteren değerdir. Referans dönemi belirtilmeden farklı anomali değerleri karşılaştırılmamalıdır.'),
    ('Sıcak hava dalgası', 'Bir bölgede normalin üzerindeki sıcaklıkların birkaç gün veya daha uzun süre devam etmesidir. Tarım, gıda saklama, insan sağlığı ve hayvan refahı üzerinde risk oluşturabilir.'),
    ('Sera gazı yoğunluğu', 'Belirli bir faaliyet, ürün veya ekonomik çıktı başına oluşan sera gazı salımıdır. Dönem ve hesap kapsamı açık olduğunda verimlilik değişimlerini izlemeye yarar.'),
    ('Sıfır atık', 'Kaynakları verimli kullanmayı, atık oluşumunu önlemeyi ve oluşan malzemeleri yeniden kullanıma kazandırmayı hedefleyen yaklaşımdır. Her atığın tamamen ortadan kalktığı iddiası yerine ölçülebilir azaltım hedefleri kullanılmalıdır.'),
    ('Sınır ötesi su', 'Birden fazla ülke veya idari bölge tarafından paylaşılan havza ve su kaynaklarıdır. Su yönetiminde iş birliği ve adil paylaşım, tarım ve gıda güvenliği açısından önemlidir.'),
    ('Soğuk zincir', 'Sıcaklığa duyarlı gıdaların üretimden tüketime kadar uygun sıcaklık aralığında tutulmasını sağlayan taşıma ve depolama sistemidir. Zincirin kesilmesi gıda güvenliği riskini artırabilir.'),
    ('Güneş ışınımı', 'Güneş’ten Dünya’ya ulaşan enerji akışıdır. Yeryüzünün aldığı enerji sıcaklıkları ve su döngüsünü etkiler; güneş enerjisi teknolojilerinde de kullanılır.'),
    ('Sulak alan', 'Suyun yıl boyunca veya belirli dönemlerde toprağı kapladığı bataklık, delta ve benzeri ekosistemlerdir. Su depolama, canlılara yaşam alanı sağlama ve karbon tutma gibi işlevleri bulunur.'),
    ('Sulama verimliliği', 'Sulama için alınan suyun ne kadarının bitkinin yararlanabileceği biçimde kök bölgesine ulaştığını ifade eder. Yöntem, bakım, zamanlama ve iklim koşulları sonucu etkiler.'),
    ('Tarımsal ormancılık', 'Ağaçları veya çalıları tarla bitkileri ya da hayvancılıkla aynı arazi sisteminde birleştiren arazi yönetimidir. Uygun tasarım gölge, habitat ve toprak koruması sağlayabilir.'),
    ('Tarımsal kuraklık', 'Toprak neminin ürünlerin su ihtiyacını karşılayamayacak düzeye düşmesiyle tarımsal gelişimin olumsuz etkilenmesidir. Yağış açığı, sıcaklık ve bitki gelişim dönemi birlikte rol oynar.'),
    ('Tarımsal meteoroloji', 'Hava ve iklim bilgilerinin tarım kararlarında kullanılmasını inceleyen alandır. Ekim, sulama, don riski ve hasat planlamasına destek olabilir.'),
    ('Tarımsal verim', 'Belirli bir alandan veya üretim biriminden elde edilen ürün miktarıdır. Karşılaştırmalarda alan, ürün türü, kalite ve üretim dönemi gibi ölçütler açıkça belirtilmelidir.'),
    ('Taşkın', 'Suyun normalde kaplamadığı alanları geçici olarak basmasıdır. Şiddetli yağış, nehir taşması veya kıyı etkileri gıda üretim alanlarına ve altyapıya zarar verebilir.'),
    ('Toprak karbonu', 'Toprakta organik maddeler ve bazı mineral biçimlerde depolanan karbondur. Toprak yönetimi karbon miktarını etkileyebilir; değişimi göstermek için düzenli ve uygun ölçüm gerekir.'),
    ('Toprak erozyonu', 'Üst verimli toprak tabakasının su veya rüzgârla taşınmasıdır. Bitki örtüsü, eğime uygun uygulamalar ve toprağı koruyan yöntemler erozyon riskini azaltabilir.'),
    ('Toprak nemi', 'Toprak gözeneklerinde bulunan su miktarıdır. Bitkilerin suya erişimini ve tarımsal kuraklık riskini değerlendirmede önemli bir göstergedir.'),
    ('Toprak sağlığı', 'Toprağın canlı bir ekosistem olarak işlevlerini sürdürebilme kapasitesidir. Yapı, organik madde, canlılık, besin döngüsü ve su tutma gibi özelliklerle değerlendirilir.'),
    ('Toprak tuzluluğu', 'Toprakta bitki gelişimini olumsuz etkileyebilecek miktarda çözünmüş tuz birikmesidir. Sulama suyu kalitesi, drenaj ve yüksek buharlaşma tuzluluk riskini etkileyebilir.'),
    ('Tüketim ayak izi', 'Bir kişinin veya topluluğun tükettiği ürün ve hizmetlerin üretim zincirindeki kaynak kullanımı ve çevresel etkileridir. Hesaplamada doğrudan etkilerin yanında tedarik zinciri de yer alabilir.'),
    ('Uyum kapasitesi', 'Bir kişi, topluluk veya ekosistemin iklim etkilerine hazırlanma, uyum sağlama ve olası zararları azaltma beceri ve kaynaklarının bütünüdür. Bilgi, altyapı, gelir ve kurumlar bu kapasiteyi etkiler.'),
    ('Üretici pazarı', 'Üreticilerin ürünlerini doğrudan tüketicilere sunduğu pazar biçimidir. Yerel gıdaya erişim sağlayabilir; ürün güvenliği, fiyat ve lojistik koşulları yine önem taşır.'),
    ('Verim açığı', 'Gerçekleşen ürün verimi ile uygun koşullarda elde edilebilecek tahmini verim arasındaki farktır. Su, besin, zararlı ve iklim kısıtları bu farkı oluşturabilir.'),
    ('Yenilenebilir enerji', 'Güneş, rüzgâr ve sürdürülebilir biçimde yönetilen biyokütle gibi doğal süreçlerle yenilenen kaynaklardan elde edilen enerjidir. Üretim biçiminin arazi ve ekosistem etkileri de değerlendirilmelidir.'),
    ('Yerel gıda', 'Belirli bir yerel veya bölgesel alanda üretilip tüketilen gıdadır. Yerel olması tek başına daha düşük çevresel etkiyi garanti etmez; üretim yöntemi, mevsim ve taşıma birlikte değerlendirilir.'),
    ('Zirai don', 'Sıcaklığın bitkilerin zarar görebileceği düzeye düşmesiyle oluşan don olayıdır. Çiçeklenme ve ürün gelişiminin hassas dönemlerinde verim kaybına yol açabilir.'),
    ('Kriyosfer', 'Dünya’daki kar, buzullar, deniz buzu ve donmuş zemin gibi donmuş su bileşenlerinin bütünüdür. Isınma kriyosferi ve buna bağlı su kaynaklarını etkiler.'),
])

TERMS.extend([
    ('Atık azaltımı', 'Üretim ve tüketim sırasında ortaya çıkan atık miktarını düşürmeye yönelik karar ve uygulamalardır. Gereksiz ambalajı önlemek ve ihtiyaç kadar satın almak atık azaltımına örnektir.'),
    ('Atık ayrıştırma', 'Atıkların türlerine ve geri kazanım yöntemlerine göre birbirinden ayrı toplanmasıdır. Doğru ayrıştırma, geri dönüştürülebilir malzemelerin kirlenmesini önlemeye yardımcı olur.'),
    ('Atık denetimi', 'Bir kurumda oluşan atıkların tür, miktar ve kaynaklarına ilişkin düzenli incelemedir. Okul veya yemekhane atık denetimi, öncelikli azaltım fırsatlarını belirlemeyi sağlar.'),
    ('Atık hiyerarşisi', 'Atıkları yönetirken önleme, yeniden kullanma, geri dönüşüm ve geri kazanımı bertaraftan önceleyen sıralamadır. En iyi seçenek genellikle atığın oluşmasını baştan engellemektir.'),
    ('Atık oluşumunu önleme', 'Bir ürün veya malzeme atığa dönüşmeden önce ihtiyacı azaltmak ya da kullanım biçimini değiştirmektir. Menü planlama ve tekrar kullanılabilir servis malzemeleri gıda hizmetlerinde önlemeye örnektir.'),
    ('Atık toplama sistemi', 'Atıkların kaynağından alınmasını, uygun biçimde taşınmasını ve işleme veya bertaraf tesislerine ulaştırılmasını sağlayan düzenektir. Ayrı toplama kutularının anlaşılır etiketlenmesi sistemin başarısını artırır.'),
    ('Atıktan kaçınma', 'Gereksiz ürün, malzeme veya gıda satın alımını ve kullanımını daha en başta önleyen yaklaşımdır. İhtiyaç listesi hazırlamak ve tek kullanımlıklardan kaçınmak bu yaklaşımın parçasıdır.'),
    ('Atıktan ürüne dönüşüm', 'Kullanılmış malzeme veya atığın yeni bir ürüne dönüştürülmesidir. Dönüşümün çevresel yararı, gereken enerjiye ve ortaya çıkan ürünün gerçekten kullanılmasına bağlıdır.'),
    ('Bertaraf', 'Atığın yeniden kullanılamadığı veya geri kazanılamadığı durumda kontrollü biçimde nihai olarak uzaklaştırılmasıdır. Düzenli depolama ve yakma bazı atıklar için kullanılan bertaraf yöntemleridir.'),
    ('Bir kullanımlık ürün', 'Kısa süre veya tek bir kullanım için tasarlanıp sonrasında atılan üründür. Tekrar kullanılabilir seçeneklere geçiş, ürünün güvenli temizliği ve toplam yaşam döngüsü dikkate alınarak planlanmalıdır.'),
    ('Biyolojik atık işleme', 'Organik atıkların mikroorganizmalar ve uygun süreçler yardımıyla işlenmesidir. Kompostlaştırma ve anaerobik çürütme, farklı koşullarda uygulanan biyolojik yöntemlerdir.'),
    ('Biyoplastik', 'Biyolojik kaynaklardan üretilebilen veya biyolojik olarak parçalanabilir özellik taşıyabilen plastik türleri için kullanılan genel addır. Her biyoplastik doğada kolayca çözünmez; ürünün sertifikası ve uygun işleme koşulu kontrol edilmelidir.'),
    ('Çevreye bırakılan atık', 'Uygun toplama ve işleme sistemi dışında sokak, su veya doğal alanlara bırakılmış atıktır. Bu atıklar canlılara zarar verebilir ve uzun süre çevrede kalabilir.'),
    ('Depozito sistemi', 'Bir ürünün ambalajı iade edildiğinde tüketiciye belirli bir bedelin geri verildiği toplama uygulamasıdır. İade teşviki ambalajların ayrı toplanıp yeniden kullanım veya geri dönüşüme gönderilmesini destekler.'),
    ('Doldurulabilir ambalaj', 'Ürün tükendikten sonra temizlenip yeniden doldurulmak üzere tasarlanan ambalajdır. Tekrar kullanımın yararlı olabilmesi için iade, yıkama ve yeniden dağıtım sistemi gerekir.'),
    ('Düşük atıklı alışveriş', 'Alışverişi planlayarak ihtiyaç fazlası gıda ve ambalaj oluşumunu azaltan tüketim biçimidir. Yeniden kullanılabilir çanta, uygun miktarda ürün ve ambalaj seçimi buna katkı sağlar.'),
    ('Ekolojik tasarım', 'Ürün ve hizmetleri tasarlarken malzeme, enerji, dayanıklılık, onarım ve kullanım sonu etkilerini birlikte gözetme yaklaşımıdır. Kolay onarılan ve uzun ömürlü ürünler atığı azaltabilir.'),
    ('Gıda artığı değerlendirme', 'Yemek hazırlama veya servis sonrası kalan gıda kısımlarının güvenli ve uygun bir amaçla değerlendirilmesidir. Önce yenilebilir kısımların tüketimi veya paylaşımı düşünülmeli, yenmeyen organik kısımlar ayrı yönetilmelidir.'),
    ('Gıda bağışı', 'Güvenli ve tüketilebilir durumdaki fazla gıdanın ihtiyaç sahiplerine ulaştırılmasıdır. Bağışta hijyen, izlenebilirlik, alerjen bilgisi ve saklama sıcaklığı korunmalıdır.'),
    ('Gıda fazlası', 'Planlanan veya ihtiyaç duyulandan fazla üretilen ya da satın alınan gıdadır. Fazlanın oluşmasını önlemek, sonradan atık yönetmekten daha etkili bir çözümdür.'),
    ('Gıda kurtarma', 'Tüketilebilir durumdaki fazla gıdanın atık olmadan önce toplanıp insan tüketimine yönlendirilmesidir. Güvenli taşıma ve zamanında dağıtım gerekir.'),
    ('Gıda yeniden dağıtımı', 'Fazla ve güvenli gıdanın üretici, işletme veya kurumdan onu kullanabilecek kişi ve kuruluşlara ulaştırılmasıdır. Etkin bir sistem, miktar ve teslim zamanını eşleştirir.'),
    ('Gıda rezervasyonu', 'Yemek hizmetlerinde hazırlanacak porsiyon veya ürün miktarını önceden talep bilgisine göre belirleme uygulamasıdır. Doğru talep tahmini fazla üretimi ve yenilebilir gıda atığını azaltabilir.'),
    ('Gıda atık hiyerarşisi', 'Yenilebilir gıda kaybını önce önlemeyi, ardından fazla gıdayı insan tüketimine kazandırmayı; uygun olmayan kısımları yem, biyolojik işleme ve en son bertarafa yönlendirmeyi esas alan öncelik sırasıdır.'),
    ('Geri dönüşüm', 'Atık malzemelerin işlenerek yeni ürün veya malzeme üretiminde hammadde olarak kullanılmasıdır. Temiz ve doğru ayrıştırılmış atıkların geri dönüşüm kalitesi daha yüksek olabilir.'),
    ('Geri dönüştürülebilir malzeme', 'Belirli bir toplama ve işleme altyapısında yeniden hammaddeye dönüştürülebilen malzemedir. Bir ürünün teorik olarak dönüştürülebilmesi, her bölgede fiilen geri dönüştürüldüğü anlamına gelmez.'),
    ('Geri kazanım', 'Atıklardan malzeme veya enerji gibi yararlı değerlerin elde edilmesidir. Geri kazanımdan önce atık oluşumunu önlemek ve ürünleri yeniden kullanmak tercih edilir.'),
    ('İleri dönüşüm', 'Kullanılmış bir malzemeyi, çoğunlukla biçimini değiştirerek yeni ve daha yüksek kullanım değerine sahip bir ürüne dönüştürmektir. Üretilen eşyanın gerçekten kullanılması ve güvenli olması önemlidir.'),
    ('İkincil hammadde', 'Geri dönüşüm veya başka bir geri kazanım süreciyle elde edilip yeni üretimde kullanılabilen malzemedir. Kullanımı bazı durumlarda yeni ham madde ihtiyacını azaltabilir.'),
    ('İsraf önleme planı', 'Gıda veya malzeme israfının nerede ve neden oluştuğunu belirleyip ölçülebilir azaltım adımları tanımlayan plandır. Sorumlular, takvim ve izleme göstergeleri içermelidir.'),
    ('Kalıntı atık', 'Önleme, yeniden kullanma ve geri kazanım adımlarından sonra geriye kalan ve mevcut sistemde başka şekilde değerlendirilemeyen atıktır. Miktarını azaltmak kaynak kullanımını iyileştirir.'),
    ('Kâğıt geri dönüşümü', 'Kullanılmış kâğıt ve kartonun ayrıştırılıp liflerinin yeni kâğıt ürünlerinde kullanılmak üzere işlenmesidir. Yağ veya gıda ile kirlenmiş kâğıtların kabul durumu yerel sisteme göre değişebilir.'),
    ('Kullanım ömrü', 'Bir ürünün işlevini güvenli ve yeterli biçimde yerine getirebildiği süredir. Dayanıklı ürün seçimi, bakım ve onarım kullanım ömrünü uzatarak atık oluşumunu azaltabilir.'),
    ('Malzeme akış analizi', 'Bir kurum, şehir veya sistemde malzemelerin nereden geldiğini, nasıl kullanıldığını ve hangi atık akışlarına dönüştüğünü inceleme yöntemidir. Kaynak kullanımını ve kayıp noktalarını görünür kılar.'),
    ('Malzeme verimliliği', 'Aynı işlevi daha az malzeme kullanarak veya malzemeyi daha uzun süre kullanarak sağlama becerisidir. Ürün tasarımı ve satın alma kararları üzerinde etkilidir.'),
    ('Organik atık', 'Bitkisel veya hayvansal kökenli, biyolojik süreçlerle parçalanabilen atıktır. Gıda artıkları, uygun biçimde ayrı toplanıp işlenirse kompost veya biyogaz üretiminde değerlendirilebilir.'),
    ('Paylaşım ekonomisi', 'Ürün ve kaynakların sahiplik yerine paylaşım, ödünç alma veya ortak kullanım yoluyla değerlendirilmesini destekleyen yaklaşımdır. Güvenli ve düzenli paylaşım, kullanılmayan ürün ihtiyacını azaltabilir.'),
    ('Plastik atık', 'Kullanım sonrası atılan plastik ürün ve ambalajlardır. Türüne ve yerel altyapıya göre yeniden kullanım veya geri dönüşüm imkânı değişir; plastiklerin çevreye bırakılması kirliliğe yol açar.'),
    ('Plastiksiz servis', 'Yemek sunumunda tek kullanımlık plastikleri önleyen ve yeniden kullanılabilir veya uygun alternatifleri tercih eden hizmet düzenidir. Hijyen, yıkama ve atık altyapısı birlikte planlanmalıdır.'),
    ('Porsiyon planlaması', 'Yemek miktarını katılımcı sayısı, tercih ve gerçek tüketim verisine göre ayarlama sürecidir. İhtiyaca uygun porsiyon seçeneği, yenilebilir tabak artığını azaltabilir.'),
    ('Tek kullanımlık ambalaj', 'Bir kez kullanıldıktan sonra atılması amaçlanan ürün ambalajıdır. Yeniden doldurulabilir veya tekrar kullanılabilir sistemler, gerekli hijyen ve lojistik koşulları sağlandığında bu ambalaj ihtiyacını azaltabilir.'),
    ('Tabak artığı', 'Yemek servis edildikten sonra tabakta yenmeden kalan gıdadır. Miktar ve nedenlerin düzenli izlenmesi porsiyon, menü ve servis düzenini iyileştirmeye yardımcı olur.'),
    ('Tersine lojistik', 'Ürün, ambalaj veya malzemenin tüketim noktasından üreticiye, toplama merkezine ya da işleme tesisine geri taşınmasıdır. Depozito ve yeniden kullanım sistemlerinde önemli rol oynar.'),
    ('Tekrar kullanım', 'Bir ürünün atık hâline gelmeden aynı veya benzer işlev için yeniden kullanılmasıdır. Dayanıklı kapların temizlenerek tekrar kullanılması ambalaj atığını azaltabilir.'),
    ('Yeniden doldurma istasyonu', 'Tüketicilerin kendi kaplarını veya iade edilebilir kapları getirerek belirli ürünleri yeniden doldurabildiği noktadır. Gıda ürünlerinde hijyen ve ölçülü dolum kuralları uygulanmalıdır.'),
    ('Yeniden kullanım sistemi', 'Ürünlerin tek kullanımdan sonra atılmak yerine toplandığı, temizlendiği ve tekrar dağıtıldığı altyapı ve işleyiştir. İade kolaylığı ve yeterli dönüş sayısı sistemin çevresel başarısını etkiler.'),
    ('Yerel atık yönetimi', 'Bir mahalle veya belediyede atıkların önlenmesi, ayrı toplanması, taşınması ve işlenmesinin yerel koşullara göre düzenlenmesidir. Hanelerin doğru bilgiye ve uygun toplama noktalarına erişmesi gerekir.'),
    ('Yemek planlaması', 'Alışveriş ve yemek hazırlığını kişi sayısı, mevcut gıda ve porsiyon ihtiyacına göre önceden düzenlemektir. Planlama, fazla satın alma ve yenilebilir gıda atığını azaltmaya yardımcı olur.'),
    ('Yemekhane atık ölçümü', 'Yemek hazırlığı, servis ve tabaklardan çıkan atıkların belirli aralıklarla tartılıp kaydedilmesidir. Sonuçlar kişi sayısı veya öğün başına hesaplanarak zaman içindeki değişim izlenebilir.'),
    ('Yemekhane fazla üretimi', 'Beklenenden fazla sayıda porsiyon hazırlanması nedeniyle tüketilmeden kalan yemek miktarıdır. Katılım tahminini iyileştirmek ve üretimi kademeli planlamak bu fazlayı azaltabilir.'),
])


class Command(BaseCommand):
    help = 'Populate the glossary with comprehensive climate, food, water, and project terms.'

    def handle(self, *args, **options):
        topics = list(Topic.objects.order_by('order'))
        for title, definition in TERMS:
            related_topic = None
            for topic in topics:
                if any(word in title.lower() or word in definition.lower() for word in topic.title.lower().split()[:2]):
                    related_topic = topic
                    break
            GlossaryTerm.objects.update_or_create(
                title=title,
                defaults={'definition': definition, 'related_topic': related_topic, 'is_published': True},
            )
        self.stdout.write(self.style.SUCCESS(f'Sözlük hazır: {GlossaryTerm.objects.filter(is_published=True).count()} terim.'))
