# Generated by Django 5.0.6 on 2026-09-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('game_type', models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli'), ('true_false', 'Doğru/Yanlış'), ('matching', 'Eşleştirme'), ('scenario', 'Senaryo')], default='multiple_choice', max_length=30)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=180)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/')),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('placeholder', 'Yakında'), ('ready', 'Hazır')], default='planned', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='learning.topic')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Başladı'), ('completed', 'Tamamlandı')], default='started', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameprogress_set', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='games.minigame')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.minigame')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameprogress',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_game_progress_per_user_game'),
        ),
    ]
